# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: 
  - 4.1.0
  
cache: packages
warnings_are_errors: false

r_packages:
  - covr

install:
  - Rscript -e "install.packages(c('devtools','reshape2','broom','gamlss','gamlss.dist','ggplot2','cowplot','DescTools','merTools','data.table','doParallel','doSNOW','future','future.apply','foreach','brokenstick'))"
  
  # only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'