#'Infant growth of 0-2 years, SMOCC data
#'
#'Longitudinal height, weight, head circumference measurements 
#'during ages 0-2 years for a representative sample of 1933 
#'Dutch children born in 1988-1989, including covariates.
#'
#'Only children with at least 6 visits were selected.
#'
#'@name smocc
#'@docType data
#'@format A list with three components: 
#'\describe{
#'\item{id}{Numeric vector of length 1933 with the \code{id} of each child.}
#'\item{child}{Tibble with 1933 rows and 53 columns containing covariates and the rasterized growth data}
#'\item{time}{Tibble with 18586 rows and 17 columns containing the measured growth data per time point.}
#'}
#'The \code{child} tibble contains the following variables: 
#'\describe{
#'\item{id}{ID, unique \code{id} of each child (numeric)}
#'\item{src}{Source, here \code{"smocc"} (factor)}
#'\item{dob}{Data of birth \code{"smocc"} (character)}
#'
#'\item{sex}{Sex, \code{"male"} or \code{"female"}}
#'\item{etn}{Etnicity, \code{"MA"}, \code{"NL"}, or \code{"TU"}}
#'\item{edu}{Educational level (typically mother), \code{"low"}, \code{"middle"}, \code{"high"}}#'
#'\item{ga}{Gestational age in completed, weeks}
#'\item{bw}{Birth weight in grammes}
#'\item{twin}{Twin, 0 = no, 1 = yes}
#'\item{smo}{Mother smoked during pregnancy, 0 = no, 1 = yes}
#'\item{agem}{Mother age when giving birth (years)}
#'\item{hgtm}{Height of mother in cm (numeric)}
#'\item{hgtf}{Height of father in cm (numeric)}
#'\item{hgt_age}{Broken stick estimate \code{hgt}, cm}
#'\item{wgt_age}{Broken stick estimate \code{wgt}, kg}
#'\item{hdc_age}{Broken stick estimate \code{hdc}, cm}
#'}
#'
#'The \code{time} tibble contains the following variables: 
#'\describe{
#'\item{src}{Source, here \code{"smocc"}}
#'\item{id}{ID, unique \code{id} of each child}
#'\item{rec}{Record number}
#'\item{nrec}{Number of child records, 6+}
#'\item{dob}{Data of birth (character)}
#'\item{dob}{Data of measurement (character)}
#'\item{age}{Decimal age}
#'\item{sex}{Sex, \code{"male"} or \code{"female"}}
#'\item{etn}{Etnicity, \code{"MA"}, \code{"NL"}, or \code{"TU"}}
#'\item{ga}{Gestational age in completed weeks}
#'\item{bw}{Birth weight in grammes}
#'\item{hgt}{Height measurement in cm}
#'\item{wgt}{Weight measurement in kg}
#'\item{hdc}{Head circ measurement in cm}
#'\item{hgt.z}{Height measurement in SDS}
#'\item{wgt.z}{Weight measurement in SDS}
#'\item{hdc.z}{Head circ measurement in SDS}
#'}
#'@source Herngreen WP, van Buuren S, van Wieringen JC, Reerink JD, Verloove-Vanhorick SP \& Ruys JH (1994). Growth in length and weight from birth to 2 years of a representative sample of Netherlands children (born in 1988-89) related to socio-economic status and other background characteristics. \emph{Annals of Human Biology}, \bold{21}, 449-463.
#'@note This dataset is property of the Netherlands Organisation for Applied Scientific Research TNO. Distribution is not permitted. 
#'Inquiries at \email{stef.vanbuuren@@tno.nl}.
#'@keywords datasets
NULL

#'SMOCC data, broken stick model export
#'
#'This object is a list with three objects: \code{hgt}, \code{wgt}, \code{hdc} and \code{bmi}. Each list member was generated by \code{export()} applied to the fitted broken stick model. This information is useful for calculating broken stick estimates for newly entered growth data
#'
#'@name smocc_bs
#'@docType data
#'@format A list with four components: 
#'\describe{
#'\item{hgt}{Object of class \code{brokenstick_export}}
#'\item{wgt}{Object of class \code{brokenstick_export}}
#'\item{hdc}{Object of class \code{brokenstick_export}}
#'\item{bmi}{Object of class \code{brokenstick_export}}
#'}
#'@keywords datasets
NULL
